config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  
  resources :game_responses
  resources :questions do
    member do
      get :review
      patch :update_status
    end
  end
  resources :categories_courses
  resources :levels
  resources :categories
  resources :courses
  resources :roles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :game_sessions, only: [:index, :show, :new, :create, :destroy] do
    member do
      get :play
      post :answer
      get :result
    end
    
    collection do
      get :history
    end
  end

  # config/routes.rb
  resources :admin, only: [:index] do
    collection do
      post 'upload_questions', to: 'admin#upload_questions'
    end
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  authenticated :user do
    root to: 'game_sessions#index', as: :authenticated_root
  end

  devise_scope :user do
    unauthenticated do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :users, only: [:index, :edit, :update, :destroy]
  resources :users do
    member do
      get :edit_password
      patch :update_password
    end
  end

  resources :kahoot_games, only: [:new, :create, :show, :destroy] do
    member do
      post :start
      post :submit_answer
      post :next_question
    end

    collection do
      get :history
    end
  end

  resources :kahoot_participants, only: [:new ,:create, :destroy]

  match "*path", to: "application#handle_not_found", via: :all
  
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :answers, allow_destroy: true  #Permitir la creación de Answer desde el modelo Question
  belongs_to :category
  belongs_to :level
  belongs_to :author, class_name: 'User', foreign_key: "author_id"
  belongs_to :revisor, class_name: 'User', foreign_key: "revisor_id", optional: true
  has_many :game_responses

  enum status: { pending: 0, approved: 1, rejected: 2 }

  def editable?(current_user)
    (self.pending? && self.author == current_user)
  end

  def reviewable?(current_user)
    (self.pending? && (self.revisor == current_user || current_user.superuser?))
  end

  def correct_answer_text
    answers.find_by(correct: true)&.answer_text
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_question, only: %i[ show edit update destroy review update_status]
  before_action :init_variables, only: %i[ new edit update create]

  NUMBER_OF_ANSWERS = 4
  # GET /questions or /questions.json
  def index
    @questions_created = Question.where(author_id: current_user.id).order(:id)
    @questions_reviewed = Question.where(revisor_id: current_user.id, status: [:approved, :rejected]).order(:id)
    @questions_pending_review =  Question.where(revisor_id: current_user.id, status: :pending).order(:id)
    case current_user.role.name
    when 'teacher'
      categories_course = CategoriesCourse.where(course_id: current_user.course_id)
      @questions_for_course = Question.where(category_id: categories_course.pluck(:category_id)).order(:id)
    when 'admin'
      @all_questions = Question.all.order(:id)
    end
  end

  # GET /questions/1 or /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
    NUMBER_OF_ANSWERS.times { @question.answers.build }
  end

  # GET /questions/1/edit
  def edit
    unless @question.editable?(current_user)
      respond_to do |format|
        format.html { redirect_to @question, notice: "No tienes permiso para editar esta pregunta. Debes ser el autor de la pregunta" }
        format.json { render :show, status: :ok, location: @question }
      end
    end
  end

  # POST /questions or /questions.json
  def create
    @question = Question.new(question_params)
    @question.author = current_user
    #@question.status = nil if question_params[:approved] == "0" #Si no se marca el check de aprobado se envia un cero
    #En la creación de la pregunta pondremos aprobado a nil y esa sera nuestro estado de pendiente

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: "Pregunta creada correctamente." }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1 or /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: "Pregunta actualizada correctamente." }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1 or /questions/1.json
  def destroy
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_path, status: :see_other, notice: "Pregunta eliminada correctamente." }
      format.json { head :no_content }
    end
  end

  def review
    unless @question.reviewable?(current_user)
      respond_to do |format|
        format.html { redirect_to @question, notice: "No tienes permiso para revisar esta pregunta." }
        format.json { render :show, status: :ok, location: @question }
      end
    end
  end

  def update_status
    unless @question.reviewable?(current_user)
      flash[:alert] = "No tienes permiso para modificar esta pregunta."
      return redirect_to questions_path
    end

    if params[:status] == "1"
      @question.update(status: :approved)
      flash[:notice] = "Pregunta aprobada correctamente."
    elsif params[:status] == "2"
      @question.update(status: :rejected)
      flash[:notice] = "Pregunta rechazada correctamente."
    else
      flash[:alert] = "Estado no válido."
    end

    redirect_to questions_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:question_text, :category_id, :level_id, :status, :author_id, :revisor_id,
      answers_attributes: [:id, :answer_text, :correct, :_destroy])
    end

    def init_variables
      case current_user.role.name
      when 'student', 'teacher'
        categories_course = CategoriesCourse.where(course_id: current_user.course_id)
        @categories = Category.where(id: categories_course.pluck(:category_id))
      when 'admin'
        @categories = Category.all
      end
      @categories_with_courses = @categories.map do |category|
        course_name = get_course_category(category.id)
        ["#{category.name} (#{course_name})", category.id]
      end
      @levels = Level.where.not(name: 'mix')
    end

    def get_course_category(category_id)
      course_category = CategoriesCourse.where(category_id: category_id)
      course = Course.where(id: course_category.first.course_id).first
      course.course_display_name
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def is_revisor?
    current_user.admin? || current_user.teacher?
  end

  def question_status_icon(question)
    if question.approved?
      '<i class="fas fa-square-check text-success" title="Aprobada"></i>'.html_safe
    elsif question.pending?
      '<i class="fas fa-clock text-secondary" title="Pendiente"></i>'.html_safe
    else
      '<i class="fas fa-square-xmark text-danger" title="Rechazada"></i>'.html_safe
    end
  end

  def get_course_category(category_id)
    course_category = CategoriesCourse.where(category_id: category_id)
    course = Course.where(id: course_category.first.course_id).first
    course.course_display_name
  end

  def get_potencial_reviewer(asker)
    if asker.superuser?
      User.where(course_id: asker.course_id)
    else
      User.where(course_id: asker.course_id).where.not(id: asker.id)
    end
  end
end

app/views/questions/_form.html.erb
<%= form_with(model: question) do |form| %> 
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h6><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h6>
      <ul>
        <% question.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row mb-3">
    <%= form.label 'Pregunta' , class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_area :question_text, required: true, class: "form-control", rows: 3 %>
    </div>
  </div>
  
  <div class="row mb-3">
    <%= form.label 'Categoría', class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.select :category_id, options_for_select(@categories_with_courses, selected: question.category_id), { prompt: "Selecciona una categoría" }, { class: "form-select mb-3", required: true } %>
    </div>
  </div>


  <div class="row mb-3">
    <%= form.label 'Nivel' , class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.collection_select :level_id, @levels, :id, :name, { prompt: "Selecciona un nivel" }, { class: "form-select mb-3", required: true} %>
    </div>
  </div>

  <div class="row mb-3">
    <%= form.label 'Asignar Revisor', class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
    <%= form.collection_select :revisor_id, get_potencial_reviewer(current_user), :id, :full_name_with_username, { prompt: "Selecciona un revisor" }, { class: "form-select mb-3", required: true} %>
  </div>

  <% if 1 == 0 and is_revisor?  %>
    <div class="row mb-3">
      <%= form.label 'Estado' , class: "col-sm-2 col-form-label" %>
      <div class="col-sm-1">
        <%= form.check_box :status, class: "form-check-input" %>
      </div>
    </div>
  <% end %>

  <hr>

  <h6>Respuestas</h6>
  <br>
  <div class="accordion accordion-flush" id="answersAccordion">
    <%= form.fields_for :answers do |answer_form| %>
      <% answer_index = answer_form.index + 1 %>

      <div class="accordion-item">
        <h2 class="accordion-header" id="heading<%= answer_index %>">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse<%= answer_index %>" aria-expanded="false" aria-controls="collapse<%= answer_index %>">
            Respuesta <%= answer_index %>
          </button>
        </h2>
        <div id="collapse<%= answer_index %>" class="accordion-collapse collapse" aria-labelledby="heading<%= answer_index %>">
          <div class="accordion-body">
            <div class="row mb-3">
              <%= answer_form.label :answer_text, "Respuesta", class: "col-sm-2 col-form-label" %>
              <div class="col-sm-10">
                <%= answer_form.text_area :answer_text, required: true, class: "form-control", rows: 3 %>
              </div>
            </div>

            <div class="row mb-3">
              <%= answer_form.label 'Correcta', class: "col-sm-2 col-form-label", for: "correctAnswer#{answer_index}" %>
              <div class="col-sm-1">
                <%= answer_form.check_box :correct, class: "form-check-input correct-checkbox", id: "correctAnswer#{answer_index}", onclick: "onlyOneCorrect(this)" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit class: "btn btn-primary", onclick: "atLeastOneCorrect()" %>
    <div>
      <%= link_to '<i class="fas fa-backward"></i> Volver'.html_safe, questions_path , class: "btn btn-dark" %>
    </div>
  </div>
  <br><br>
<% end %>

<script>
  function onlyOneCorrect(selectedCheckbox) {
    const checkboxes = document.querySelectorAll(".correct-checkbox");
    
    checkboxes.forEach((checkbox) => {
      if (checkbox !== selectedCheckbox) {
        checkbox.checked = false;
      }
    });
  }

  function atLeastOneCorrect(){
    let correctAnswers = document.querySelectorAll('#answersAccordion input[type="checkbox"][name*="[correct]"]:checked');
      if (correctAnswers.length === 0) {
        event.preventDefault(); // Evitar el envío del formulario
        alert("Debes marcar al menos una respuesta como correcta.");
      }
  }
</script>

app/views/questions/_info.html.erb
<div class="form-floating mb-3">
  <textarea class="form-control" id="floatingTextarea" style="height: 150px" readonly>
    <%= question.question_text %>
  </textarea>
  <label for="floatingTextarea">Pregunta</label>
</div>

<div class="row g-2 mb-3">
  <div class="col-md">
    <div class="form-floating">
      <input type="input" class="form-control" id="floatingInputCategory" readonly value= "<%= question.category.name %> (<%=  get_course_category(question.category.id) %>)">
      <label for="floatingInputCategory">Categoría</label>
    </div>
  </div>

  <div class="col-md">
    <div class="form-floating">
      <input type="input" class="form-control" id="floatingInputLevel" readonly value= "<%= question.level.name %>">
      <label for="floatingInputLevel">Nivel</label>
    </div>
  </div>
</div>

<div class="row g-2 mb-3">
  <div class="col-md">
    <div class="form-floating">
      <input type="input" class="form-control" id="floatingInputAuthor" readonly value= "<%= question.author.full_name_with_username %>">
      <label for="floatingInputAuthor">Autor</label>
    </div>
  </div>

  <div class="col-md">
    <div class="form-floating">
      <input type="input" class="form-control" id="floatingInputRevisor" readonly value= "<%= question.revisor.nil? ? '' : question.revisor.full_name_with_username %>">
      <label for="floatingInputRevisor">Revisor</label>
    </div>
  </div>
</div>

<div class="accordion" id="accordionAnswers">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingAnswers">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseAnswers" aria-expanded="true" aria-controls="collapseOne">
        Respuestas
      </button>
    </h2>

    <div id="collapseAnswers" class="accordion-collapse collapse" aria-labelledby="headingAnswers" data-bs-parent="#accordionAnswers">
      <div class="accordion-body">
        <% question.answers.each_with_index  do |answer, index| %>
          <div class="form-floating mb-3">
            <textarea class="form-control" id="floatingTextarea" style="height: 150px" readonly>
              <%= answer.answer_text %>
            </textarea>
            <label for="floatingTextarea">Respuesta <%= index + 1 %> <%= '<i class="fas fa-square-check text-success" title="Aprobada"></i>'.html_safe if (answer.correct && (current_user == question.revisor || current_user == question.author || current_user.superuser?) && question.pending?) %></label>
          </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/questions/_questions_table.html.erb
<div class="table-responsive" style="max-height: 500px; overflow-y: auto; border: 1px solid #ddd; border-radius: 8px;">
  <table class="table table-striped mb-0">
    <thead>
      <tr>
        <th>ID</th>
        <th>Pregunta</th>
        <th>Categoría</th>
        <th>Nivel</th>
        <th>Estado</th>
        <th>Autor</th>
        <th>Revisor</th>
        <th colspan="3">Acciones</th>
      </tr>
    </thead>
    <tbody>
      <% questions.each do |question| %>
        <tr>
          <td><%= question.id %></td>
          <td><%= question.question_text %></td>
          <td><%= question.category.name %> (<%= get_course_category(question.category.id) %>)</td>
          <td><%= question.level.name %></td>
          <td class="text-center">
            <%= question_status_icon(question) %>
          </td>
          <td><%= question.author.username %></td>
          <td><%= question.revisor.username unless question.revisor.nil? %></td>
          <td>
            <btn title="">
            <%= link_to '<i class="fas fa-magnifying-glass" title="Ver pregunta"></i>'.html_safe, question, class: 'btn btn-primary btn-sm' %>
            <%= link_to '<i class="far fa-pen-to-square" title="Editar pregunta"></i>'.html_safe, edit_question_path(question), class: 'btn btn-warning btn-sm' if question.editable?(current_user) %>
            <%= link_to '<i class="fas fa-magnifying-glass" title="Revisar pregunta"></i>'.html_safe, review_question_path(question), class: 'btn btn-warning btn-sm' if question.reviewable?(current_user) %>
            <%= link_to '<i class="far fa-trash-can" title="Eliminar pregunta"></i>'.html_safe, question, method: :delete, data: { confirm: '¿Estás seguro?' }, class: 'btn btn-danger btn-sm' if current_user.superuser? %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

app/views/questions/edit.html.erb
<div class="container text-center mt-5">
<h1>Editar Pregunta</h1>
<br>
<%= render 'form', question: @question %>
</div>

app/views/questions/index.html.erb
<div class="container mt-4">
  <h2 class="mb-4 text-center">
    Gestión de Preguntas
    <%= link_to 'Nueva Pregunta <i class="fas fa-circle-plus"></i>'.html_safe, new_question_path, class: "btn btn-success" %>
    <% if current_user.superuser? %>
      <%= link_to 'Cargar Preguntas <i class="fas fa-cloud-arrow-up"></i>'.html_safe, admin_index_path, data: {turbolinks: false }, class: "btn btn-primary" %>
    <% end %>
  </h2>

  <ul class="nav nav-tabs" id="questionsTab" role="tablist">
    <li class="nav-item" role="presentation">
      <button class="nav-link active" id="created-questions-tab" data-bs-toggle="tab" data-bs-target="#created-questions" type="button" role="tab" aria-controls="created-questions" aria-selected="true">
        Mis Preguntas
      </button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="pending-review-questions-tab" data-bs-toggle="tab" data-bs-target="#pending-review-questions" type="button" role="tab" aria-controls="pending-review-questions" aria-selected="false">
        Preguntas pendientes de revisar
      </button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="reviewed-questions-tab" data-bs-toggle="tab" data-bs-target="#reviewed-questions" type="button" role="tab" aria-controls="reviewed-questions" aria-selected="false">
        Preguntas Revisadas
      </button>
    </li>
    <% if current_user.role.name == 'teacher' %>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="course-questions-tab" data-bs-toggle="tab" data-bs-target="#course-questions" type="button" role="tab" aria-controls="course-questions" aria-selected="true">
          Preguntas del Curso de <%= current_user.course.course_display_name  unless current_user.course.blank? %>
        </button>
      </li>
    <% elsif current_user.role.name == 'admin' %>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="all-questions-tab" data-bs-toggle="tab" data-bs-target="#all-questions" type="button" role="tab" aria-controls="all-questions" aria-selected="true">
          Todas las Preguntas
        </button>
      </li>
    <% end %>
  </ul>

  <div class="tab-content mt-3" id="questionsTabContent">
      <div class="tab-pane fade show active" id="created-questions" role="tabpanel" aria-labelledby="created-questions-tab">
        <%= render 'questions_table', questions: @questions_created %>
      </div>
      <div class="tab-pane fade" id="pending-review-questions" role="tabpanel" aria-labelledby="pending-review-questions-tab">
        <%= render 'questions_table', questions: @questions_pending_review %>
      </div>
      <div class="tab-pane fade" id="reviewed-questions" role="tabpanel" aria-labelledby="reviewed-questions-tab">
        <%= render 'questions_table', questions: @questions_reviewed %>
      </div>
    <% if current_user.role.name == 'teacher' %>
      <div class="tab-pane fade" id="course-questions" role="tabpanel" aria-labelledby="course-questions-tab">
        <%= render 'questions_table', questions: @questions_for_course %>
      </div>
    <% elsif current_user.role.name == 'admin' %>
      <div class="tab-pane fade" id="all-questions" role="tabpanel" aria-labelledby="all-questions-tab">
        <%= render 'questions_table', questions: @all_questions %>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/new.html.erb
<div class="container text-center mt-5">
  <h1 class="mb-3">Nueva Pregunta</h1>
  <%= render 'form', question: @question %>
</div>

app/views/questions/review.html.erb
<div class="container text-center">
  <h1 class="mb-3">Revisar Pregunta
    <span class="badge">
      <%= question_status_icon(@question) %>
    </span>
  </h1>

  <%= render 'info', question: @question %>

  <div class="mb-3"></div>

  <div class= "actions mb-3">
    <%= form_with url: update_status_question_path(@question), method: :patch do %>
      <button type="submit" name="status" value="1" class="btn btn-success">Aprobar</button>
      <button type="submit" name="status" value="2" class="btn btn-danger">Rechazar</button>
    <% end %>
    <div>
      <%= link_to '<i class="fas fa-backward"></i> Volver'.html_safe, questions_path , class: "btn btn-dark" %>
    </div>
  </div>
</div>

app/views/questions/show.html.erb
<div class="container text-center mt-5">
  <h1 class="mb-3">Ver Pregunta
    <span class="badge">
      <%= question_status_icon(@question) %>
    </span>
  </h1>

  <%= render 'info', question: @question %>

  <div class="mb-3"></div>

  <div class= "actions mb-3">
    <%= link_to 'Editar <i class="far fa-pen-to-square"></i>'.html_safe, edit_question_path(@question), class: "btn btn-warning" if @question.editable?(current_user) %>
    <div>
      <%= link_to '<i class="fas fa-backward"></i> Volver'.html_safe, questions_path , class: "btn btn-dark" %>
    </div>
  </div>
</div>