config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  
  resources :game_responses
  resources :questions do
    member do
      get :review
      patch :update_status
    end
  end
  resources :categories_courses
  resources :levels
  resources :categories
  resources :courses
  resources :roles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :game_sessions, only: [:index, :show, :new, :create, :destroy] do
    member do
      get :play
      post :answer
      get :result
    end
    
    collection do
      get :history
    end
  end

  # config/routes.rb
  resources :admin, only: [:index] do
    collection do
      post 'upload_questions', to: 'admin#upload_questions'
    end
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  authenticated :user do
    root to: 'game_sessions#index', as: :authenticated_root
  end

  devise_scope :user do
    unauthenticated do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :users, only: [:index, :edit, :update, :destroy]
  resources :users do
    member do
      get :edit_password
      patch :update_password
    end
  end

  resources :kahoot_games, only: [:new, :create, :show, :destroy] do
    member do
      post :start
      post :submit_answer
      post :next_question
    end

    collection do
      get :history
    end
  end

  resources :kahoot_participants, only: [:new ,:create, :destroy]

  match "*path", to: "application#handle_not_found", via: :all
  
end

app/models/kahoot_game.rb
class KahootGame < ApplicationRecord
  belongs_to :host, class_name: 'User', foreign_key: "host_id"
  belongs_to :category
  belongs_to :level
  has_many :kahoot_participants, dependent: :destroy
  has_many :kahoot_questions, dependent: :destroy
  has_many :questions, through: :kahoot_questions

  enum status: { waiting: 0, in_progress: 1, finished: 2, canceled: 3 }

  validates :status, presence: true

  NUMBER_OF_QUESTIONS_PER_KAHOOT = 3

  def add_questions
    return true if questions.any?

    if level.name = "mix"
      selected_questions = Question.where(category: category, status: :approved).order(Arel.sql("RANDOM()")).limit(NUMBER_OF_QUESTIONS_PER_KAHOOT)
    else
      selected_questions = Question.where(category: category, level: level, status: :approved).order(Arel.sql("RANDOM()")).limit(NUMBER_OF_QUESTIONS_PER_KAHOOT)
    end

    selected_questions.each_with_index do |question, index|
      kahoot_questions.create!(question: question, order: index)
    end

    self.current_question_index = 0
    save!
  end

  def self.can_add_questions?(category_id, level_id) #Comprobar si hay suficientes preguntas para empezar la partida
    level = Level.find(level_id)
    category = Category.find(category_id)
    if level && category
      if level.name == "mix"
        Question.where(category_id: category_id, status: :approved).count >= NUMBER_OF_QUESTIONS_PER_KAHOOT
      else
        Question.where(category_id: category_id, level_id: level_id, status: :approved).count >= NUMBER_OF_QUESTIONS_PER_KAHOOT
      end
    end
  end

  def current_question
    kahoot_questions.find_by(order: current_question_index)
  end

  def has_next_question?
    current_question_index < (kahoot_questions.count - 1)
  end

  def next_question
    kahoot_questions.find_by(order: current_question_index+1) if has_next_question?
  end

  def advance_question #actualizar el index cuando se va a enviar la siguiente pregunta
    update(current_question_index: current_question_index + 1) if has_next_question?
  end

  def ranking
    kahoot_participants.joins(:user).select("users.username, kahoot_participants.score").order(score: :desc).map { |p| { username: p.username, score: p.score } }
  end
end

app/controllers/kahoot_games_controller.rb
class KahootGamesController < ApplicationController
  include GameSessionsHelper
  before_action :authenticate_user!
  before_action :check_permissions, only: %i[new start create]
  before_action :set_kahoot_game, only: %i[show start destroy submit_answer next_question]
  before_action :check_participants, only: %i[show]

  def new
    @kahoot_game = KahootGame.new
    @levels = Level.all
    case current_user.role.name
    when 'teacher'
      categories_course = CategoriesCourse.where(course_id: current_user.course_id)
      @categories = Category.where(id: categories_course.pluck(:category_id))
    when 'admin'
      @categories = Category.all
    end
  end

  def create
    @kahoot_game = KahootGame.new(kahoot_game_params)
    @kahoot_game.host = current_user

    if KahootGame.can_add_questions?(kahoot_game_params[:category_id], kahoot_game_params[:level_id])
      if @kahoot_game.save
        @kahoot_game.add_questions
        redirect_to @kahoot_game, notice: 'Kahoot creado correctamente.'
      else
        render :new, status: :unprocessable_entity
      end
    else
      redirect_to new_kahoot_game_path, alert: "No se ha podido crear el Kahoot. No hay suficientes preguntas disponibles en esta categoría y nivel."
    end
  end

  def show
    @participants = @kahoot_game.kahoot_participants
  end

  def start
    if @kahoot_game.host == current_user
      @kahoot_game.update(status: :in_progress)

      @kahoot_game.current_question.update(sent_at: Time.current)

      KahootGameChannel.broadcast_to(@kahoot_game, { type: "game_started" })
      redirect_to @kahoot_game
    else
      redirect_to @kahoot_game, alert: "No tienes permisos para iniciar esta partida."
    end
  end

  def submit_answer
    participant = @kahoot_game.kahoot_participants.find_by(user: current_user)
    host = @kahoot_game.host

    unless participant
      return render json: {type: "", status: "error" ,message: "No estás en la partida"}, status: :forbidden
    end

    kahoot_question = @kahoot_game.current_question
    unless kahoot_question
      return render json: { error: "La pregunta no está en la partida." }, status: :unprocessable_entity
    end

    if KahootResponse.exists?(kahoot_participant: participant, kahoot_question: kahoot_question)
      return render json: { error: "Ya has respondido a esta pregunta." }, status: :unprocessable_entity
    end

    question = kahoot_question.question
    selected_answer = question.answers.find_by(id: params[:answer_id])
    
    unless selected_answer
      return render json: { error: "Respuesta no válida." }, status: :unprocessable_entity
    end

    correct = selected_answer.correct
    answered_at = Time.current
    score = correct ? calculate_score(answered_at, kahoot_question.sent_at) : 0
    
    KahootResponse.create!(
      kahoot_participant: participant,
      kahoot_question: kahoot_question,
      answered_at: answered_at,
      correct: correct,
      score: score
    )

    participant.update(score: participant.score + score)

    total_responses = kahoot_question.kahoot_responses.count

    KahootGameChannel.broadcast_to(participant, {
      type: "answer_feedback",
      correct: correct,
      question_score: score,
      total_score: participant.score
    })

    KahootGameChannel.broadcast_to(host, {
      type: "update_counter",
      count: total_responses
    })

    head :ok
  rescue => e
    render json: { status: "error", message: e.message }, status: :unprocessable_entity
  end
  
  def next_question
    return head :forbidden unless current_user == @kahoot_game.host

    if @kahoot_game.has_next_question?
      @kahoot_game.advance_question
      send_question
    else
      @kahoot_game.update(status: :finished)
      if @kahoot_game.finished?
        ranking = @kahoot_game.ranking
        KahootGameChannel.broadcast_to(@kahoot_game, { type: "game_finished", ranking: ranking })
      end
      
    end
  end

  def history
    @participations = KahootParticipant
    .includes(:kahoot_game)
    .where(user_id: current_user.id, kahoot_games: { status: :finished })
    .references(:kahoot_game)
    .order(created_at: :desc)

    @hosted_games= KahootGame.where(host_id: current_user.id) if current_user.superuser?
  end

  def destroy
    if @kahoot_game.host == current_user
      participants = @kahoot_game.kahoot_participants
      participants.each do |participant|
        KahootGameChannel.broadcast_to(participant, { type: "game_canceled" })
      end
      @kahoot_game.update(status: :canceled)
      redirect_to new_kahoot_game_path, notice: "Partida cancelada."
    else
      redirect_to @kahoot_game, alert: "No puedes cancelar esta partida."
    end
  end

  private
  def calculate_score(answered_at, sent_at)
    max_score = 1000
    penalty_per_second = 20
    min_score = 100

    return if answered_at.nil?

    sent_time = sent_at
    return if sent_time.nil?

    response_time = (answered_at - sent_time).to_i
    [max_score - (response_time * penalty_per_second), min_score].max
  end

  def set_kahoot_game
    @kahoot_game = KahootGame.find(params[:id])
  end

  def kahoot_game_params
    params.require(:kahoot_game).permit(:category_id, :level_id)
  end

  def check_permissions
    unless current_user.superuser?
      redirect_to authenticated_root_path, alert: "No tienes permiso para crear una partida kahoot."
    end
  end

  def check_participants
    if current_user.id != @kahoot_game.host.id
      unless @kahoot_game.kahoot_participants.collect(&:user_id).include?(current_user.id)
        redirect_to new_kahoot_participant_path, alert: "Debes unirte a la partida primero."
      end
    end
  end

  def send_question
    host = @kahoot_game.host
    participants = @kahoot_game.kahoot_participants
    kahoot_question = @kahoot_game.current_question
    question = kahoot_question.question
    if question
      kahoot_question.update(sent_at: Time.current)
      answers = get_random_answers(question)

      participants.each do |participant|
        KahootGameChannel.broadcast_to(participant, {
          type: "new_question",
          host: "false",
          index_question: @kahoot_game.current_question_index + 1,
          question: {
            id: question.id,
            text: question.question_text,
            answers: answers.map { |answer| { id: answer.id, answer_text: answer.answer_text } },
          } 
        })
      end

      KahootGameChannel.broadcast_to(host, {
        type: "new_question",
        host: "true",
        index_question: @kahoot_game.current_question_index + 1,
        question: {
          id: question.id,
          text: question.question_text,
          answers: answers.map { |answer| { id: answer.id, answer_text: answer.answer_text } },
        } 
      })

      KahootGameChannel.broadcast_to(host, {
        type: "update_counter",
        count: 0
      })

      head :ok
    end
  end
end

app/helpers/kahoot_games_helper.rb
module KahootGamesHelper

  def get_kahoot_participant(user, kahoot_game)
    user.kahoot_participants.find_by(kahoot_game: kahoot_game)
  end

  def check_duplicate_answers(user, kahoot_question)
    kahoot_participant = get_kahoot_participant(user, kahoot_question.kahoot_game)
    KahootResponse.exists?(kahoot_participant: kahoot_participant, kahoot_question: kahoot_question)
  end

  def get_category(participant)
    participant.kahoot_game.category
  end

  def get_category_by_game(game)
    game.category
  end

  def get_level_by_game(game)
    game.level
  end

  def get_number_of_participants(game)
    game.kahoot_participants&.count || 0
  end
  
  def get_level(participant)
    participant.kahoot_game.level
  end
end

app/views/kahoot_games/_canceled.html.erb
<div class="container d-flex justify-content-center my-5">
  <div class="card text-center shadow p-4 d-flex flex-column" style="width: 80rem; min-height: 20rem;">
    <h3 class="card-title mb-4 text-danger">!Partida Cancelada¡</h3>
    <h5 class="card-subtitle mb-3 text-muted">Intenta unirte a una nueva partida</h5>
    <div class="d-flex flex-row justify-content-center mt-5">
      <%= button_to "Unirte a una nueva partida", new_kahoot_participant_path, method: :get, class: "btn btn-primary btn-lg mx-2" %>
    </div>
  </div>
</div>

app/views/kahoot_games/_finished.html.erb
<style>
  .podium {
    width: 120px;
    text-align: center;
    transition: transform 0.5s ease-in-out;
  }

  #first_place {
    transform: translateY(-20px);
  }

  #second_place {
    transform: translateY(0);
  }

  #third_place {
    transform: translateY(10px);
  }
</style>
<% players = @kahoot_game.ranking if @kahoot_game.finished? %>
<div class="container text-center mt-5">
  <h3 class="fw-bold text-primary">🏆 <span class="badge rounded-pill bg-primary">Ranking Final</span> 🏆</h3>

  <div class="d-flex justify-content-center align-items-end gap-3 mt-5 mb-4">
    <div id="second_place" class="podium bg-secondary text-white p-3 rounded">
      <h4>🥈</h4>
      <p class="fw-bold fs-5" id="second_username"><%= players[1][:username] if (players.present? && players[1])%></p>
      <p class="fw-bold" id="second_score"><%= players[1][:score] if (players.present? && players[1]) %></p>
    </div>

    <div id="first_place" class="podium bg-warning text-dark p-4 rounded">
      <h3>🥇</h3>
      <p class="fw-bold fs-4" id="first_username"><%= players[0][:username] if (players.present? && players[0]) %></p>
      <p class="fw-bold fs-5" id="first_score"><%= players[0][:score] if (players.present? && players[0]) %></p>
    </div>

    <div id="third_place" class="podium bg-info text-white p-3 rounded">
      <h4>🥉</h4>
      <p class="fw-bold fs-5" id="third_username"><%= players[2][:username] if (players.present? && players[2]) %></p>
      <p class="fw-bold" id="third_score"><%= players[2][:score] if (players.present? && players[2]) %></p>
    </div>
  </div>

  <div class="table-responsive mb-2" style="max-height: 300px; overflow-y: auto; border: 1px solid #ddd; border-radius: 8px;">
  <table class="table table-striped mb-0">
      <thead>
        <tr>
          <th>Puesto</th>
          <th>Nombre</th>
          <th>Puntuación</th>
        </tr>
      </thead>
      <tbody id="other_players">
        <% unless players.blank? %>
          <% players.drop(3).each_with_index do |player, index| %>
            <tr>
              <td>#<%= index + 4 %></td>
              <td><%= player[:username] %></td>
              <td><%= player[:score] %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/kahoot_games/_in_progress.html.erb
<style>
  .btn-success {
    background-color: #28a745 !important;
    color: white !important;
  }

  .btn-danger {
    background-color: #dc3545 !important;
    color: white !important;
  }

  .answer-button, .answer-button-host {
    transition: transform 0.2s ease, box-shadow 0.2s ease;
    cursor: pointer;
  }

  .answer-button:hover, .answer-button-host:hover {
    transform: scale(1.05);
    box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.2);
  }

  .fade-alert {
    opacity: 0;
    transition: opacity 0.5s ease;
  }

  .fade-alert.show {
    opacity: 1;
  }
</style>

  <% 
    index_question = @kahoot_game.current_question_index
    question = @kahoot_game.current_question.question
    answers = get_answers(question)
    number_of_questions = @kahoot_game.kahoot_questions.count
  %>
  <body data-kahoot-game-id="<%= @kahoot_game.id %>">
    <div class="container py-5 text-center">
      <% if @kahoot_game.host == current_user && @kahoot_game.in_progress? %>
        <span id="alert_player_left" class="my-2 fs-6 badge rounded-pill bg-warning text-dark fade-alert">Un participante ha abandonado la partida</span>
      <% end %>
      <div class="d-flex justify-content-between align-items-center mb-4">
        <h4 class="fw-bold">
          <span class="badge rounded-pill bg-primary">
            Pregunta <span id="index_question_container"><%= index_question + 1 %></span> de <%= number_of_questions %>
          </span>
        </h4>
        
        <% if @kahoot_game.host == current_user && @kahoot_game.in_progress? %>
          <h4>
            <button id="next_question_button" class="btn btn-outline-primary flex-shrink-0 rounded-pill">
              Siguiente Pregunta
            </button>
           </h4>
        <% end %>
        <% if @kahoot_game.host == current_user %>
          <h4 class="fw-bold">
            <span class="badge rounded-pill bg-secondary">
              Respuestas <span id="counter_participants_response_container">0</span>/<span id="counter_participants_container"><%= @kahoot_game.kahoot_participants.count %></span>
            </span>
          </h4>
        <% end %>

        <% unless @kahoot_game.host == current_user %>
          <h4 class="fw-bold">
            <span class="badge rounded-pill bg-success">
              Puntuación: <span id="score_participant_container"><%= get_kahoot_participant(current_user, @kahoot_game).score %></span>
            </span>
          </h4>
        <% end %>
      </div>

      <div class="text-center mb-5">
        <h5 class="text-muted" title="Categoría"><%= @kahoot_game.category.name %> <span title="Nivel" class="badge rounded-pill bg-<%= @kahoot_game.level.get_color %>"><%= @kahoot_game.level.name %></span></h5>
        <h3 id="question_container" class="fw-bold text-dark" title="Pregunta"><%= question.question_text %> </h3>
      </div>

      <div id="answers_container" class="row row-cols-1 row-cols-md-2 g-4">
        <% answers.each do |answer| %>
          <div class="col">
            <% if @kahoot_game.host == current_user or check_duplicate_answers(current_user, @kahoot_game.current_question) %>
              <button type="button" class="answer-button-host btn btn-outline-primary btn-lg w-100 py-3 shadow-sm" disabled>
                <%= answer.answer_text %>
              </button>
            <% else %>
              <button type="button" class="answer-button btn btn-outline-primary btn-lg w-100 py-3 shadow-sm" data-answer-id="<%= answer.id %>" data-answer-correct="<%= answer.correct %>">
                <%= answer.answer_text %>
              </button>
            <% end %>
          </div>
        <% end %>
      </div>
      <div id="send_answer_container" class="text-center mt-5">
        <button id="submit_answer_button" type="button" class="btn btn-primary btn-lg" disabled>Enviar</button>
        
        <% if check_duplicate_answers(current_user, @kahoot_game.current_question) %>
          <div id="alert_duplicate_answer_container">
           <span class="badge rounded-pill bg-warning text-dark">Ya has respondido a esta pregunta.</span>
          </div>
        <% end %>
      </div>
    </div>
  </body>

  <script>
    document.addEventListener("DOMContentLoaded", function () {
      const submitButton = document.getElementById("submit_answer_button");
      const nextQuestionButton = document.getElementById("next_question_button");
      let selectedAnswerId = localStorage.getItem("selectedAnswer");
      localStorage.removeItem("selectedAnswer");

      function selectAnswer(button) {
        document.querySelectorAll(".answer-button").forEach(btn => {
          btn.classList.remove("btn-primary");
          btn.classList.add("btn-outline-primary");
        });

        button.classList.remove("btn-outline-primary");
        button.classList.add("btn-primary");

        selectedAnswerId = button.dataset.answerId;
        localStorage.setItem("selectedAnswer", selectedAnswerId);

        submitButton.disabled = false;
      }

      document.querySelectorAll(".answer-button").forEach(button => {
        button.addEventListener("click", function () {
          selectAnswer(button);
        });

        //Volver a marcar el btn seleccionado si el usuario recarga la página
        if (selectedAnswerId && selectedAnswerId === button.dataset.answerId) {
          selectAnswer(button);
        }
      });

      if (submitButton) {
        submitButton.addEventListener("click", function () {
          if (selectedAnswerId) {
            console.log("Respuesta enviada:", selectedAnswerId);
            const kahootGameId = document.body.dataset.kahootGameId;

            fetch(`/kahoot_games/${kahootGameId}/submit_answer`, {
              method: "POST",
              headers: {
                "Content-Type": "application/json",
                "X-CSRF-Token": document.querySelector("meta[name='csrf-token']").content,
              },
              body: JSON.stringify({ answer_id: selectedAnswerId }),
            })
            .then(response => {
              if (response.ok) {
                console.log("Respuesta procesada correctamente");
                submitButton.disabled = true;
              } else {
                console.error("Error en la respuesta:", response.status);
              }
            })
            .catch(error => console.error("Error enviando respuesta:", error));
          }
        });
      }

      if (nextQuestionButton) {
        nextQuestionButton.addEventListener("click", function () {
          const kahootGameId = document.body.dataset.kahootGameId;

          fetch(`/kahoot_games/${kahootGameId}/next_question`, {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              "X-CSRF-Token": document.querySelector("meta[name='csrf-token']").content,
            }
          })
          .then(response => {
            if (response.ok) {
              console.log("Siguiente pregunta enviada");
            } else {
              console.error("Error enviando siguiente pregunta");
            }
          })
          .catch(error => console.error("Error en la solicitud:", error));
        });
      }
    });
  </script>



app/views/kahoot_games/_waiting.html.erb
<div class="container d-flex justify-content-center my-5">
  <div class="card text-center shadow p-4 d-flex flex-column" style="width: 80rem; min-height: 20rem;">
    <h3 class="card-title mb-4">Partida en espera...</h3>
    <div class="flex-grow-1 overflow-auto px-3">
      <% if @kahoot_game.host == current_user %>
        <h2 class="mb-3">
          <span class="badge bg-secondary">PIN de juego: <%= @kahoot_game.id %></span>
        </h2>
      <% end %>
      <div class="container">
        <span class="my-2 fs-6 font-monospace badge rounded-pill bg-warning text-dark">Esperando participantes...</span>
        <div class="row row-cols-1 row-cols-md-4 g-3" id="participants_container">
          <% @participants.each do |participant| %>
            <div class="col participant" data-user-id="<%= participant.user.id %>">
              <div class="p-2 bg-light border rounded"><%= participant.user.username %></div>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="d-flex flex-row justify-content-center mt-5">
      <% if current_user == @kahoot_game.host %>
        <%= button_to "Iniciar Partida", start_kahoot_game_path(@kahoot_game), id:"start_game_btn", method: :post, class: "btn btn-primary btn-lg mx-2", disabled: @participants.count == 0 %>
        <%= button_to "Cancelar Partida", kahoot_game_path(@kahoot_game), method: :delete, class: "btn btn-danger btn-lg mx-2" %>
      <% else %>
        <%= button_to "Dejar la Partida", kahoot_participant_path(get_kahoot_participant(current_user, @kahoot_game)), 
            method: :delete, 
            data: { confirm: "¿Seguro que quieres salir de la partida?" }, 
            class: "btn btn-danger btn-lg mx-2" %>
      <% end %>
    </div>
  </div>
</div>


app/views/kahoot_games/history.html.erb
<div class="container mt-4">
  <h1 class="mb-4 text-center">Historial de Partidas Kahoot</h1>

  <ul class="nav nav-tabs" id="rankingTabs" role="tablist">
    <li class="nav-item" role="presentation">
      <button class="nav-link active" id="participations-tab" data-bs-toggle="tab" data-bs-target="#participations" type="button" role="tab" aria-controls="participations" aria-selected="true">Participaciones</button>
    </li>
    <% if current_user.superuser? %>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="hosts-tab" data-bs-toggle="tab" data-bs-target="#hosts" type="button" role="tab" aria-controls="hosts" aria-selected="false">Hosted</button>
    </li>
    <% end %>
  </ul>

  <div class="tab-content mt-4" id="userTabsContent">
    <div class="tab-pane fade show active" id="participations" role="tabpanel" aria-labelledby="participations-tab">
      <div class="table-responsive" style="max-height: 500px; overflow-y: auto; border: 1px solid #ddd; border-radius: 8px;">
        <table class="table table-striped mb-0">
          <thead>
            <tr>
              <th>ID</th>
              <th>Categoría</th>
              <th>Nivel</th>
              <th>Puntuación</th>
              <th>Fecha</th>
            </tr>
          </thead>

          <tbody>
            <% @participations.each do |participant| %>
              <% category = get_category(participant) %>
              <% level = get_level(participant) %>
              <tr>
                <td><%= participant.kahoot_game_id %></td>
                <td><%= category.name %> (<%= get_course_category(category.id) %>)</td>
                <td><span class="badge rounded-pill bg-<%= level.get_color %>"><%= level.name %></span></td>
                <td><%= participant.score %> puntos</td>
                <td><%= participant.created_at.strftime("%d/%m/%Y %H:%M") %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>

    <% if current_user.superuser? %>
    <div class="tab-pane fade" id="hosts" role="tabpanel" aria-labelledby="hosts-tab">
      <div class="table-responsive" style="max-height: 500px; overflow-y: auto; border: 1px solid #ddd; border-radius: 8px;">
        <table class="table table-striped mb-0">
          <thead>
            <tr>
              <th>ID</th>
              <th>Categoría</th>
              <th>Nivel</th>
              <th>Nº participantes</th>
              <th>Fecha</th>
            </tr>
          </thead>

          <tbody>
            <% @hosted_games.each do |game| %>
              <% category = get_category_by_game(game) %>
              <% level = get_level_by_game(game) %>
              <% number_of_participants = get_number_of_participants(game) %>
              <tr>
                <td><%= game.id %></td>
                <td><%= category.name %> (<%= get_course_category(category.id) %>)</td>
                <td><span class="badge rounded-pill bg-<%= level.get_color %>"><%= level.name %></span></td>
                <td><%= number_of_participants %></td>
                <td><%= game.created_at.strftime("%d/%m/%Y %H:%M") %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <% end %>
  </div>
  <br>
</div>

app/views/kahoot_games/new.html.erb
<div class="container d-flex justify-content-center my-5">
  <div class="card text-center shadow p-4" style="width: 50rem;">
    <h5 class="card-title mb-4">Crear Kahoot</h5>
    <%= form_with(model: @kahoot_game, url: kahoot_games_path, local: true) do |form| %>
      <div class="row mb-3">
        <%= form.label 'Categoría' , class: "col-sm-2 col-form-label" %>
        <div class="col-sm-10">
          <%= form.collection_select :category_id, @categories, :id, :name_with_course, { prompt: "Selecciona una categoría" }, { class: "form-select mb-3", required: true} %>
        </div>
      </div>

      <div class="row mb-3">
        <%= form.label 'Nivel' , class: "col-sm-2 col-form-label" %>
        <div class="col-sm-10">
          <%= form.collection_select :level_id, @levels, :id, :name, { prompt: "Selecciona un nivel" }, { class: "form-select mb-3", required: true} %>
        </div>
      </div>

      <div>
        <%= form.submit "Iniciar kahoot!", class: "btn btn-primary btn-lg" %>
      </div>
    <% end %>
  </div>
</div>

app/views/kahoot_games/show.html.erb
<div id="overlay" class="d-none position-fixed top-0 left-0 w-100 h-100 d-flex flex-column align-items-center justify-content-center" 
    style="z-index: 9999; background-color: rgba(0, 0, 0, 0.5);">
  <div class="p-5 bg-light rounded shadow-lg text-center">
    <div id="feedback_icon" class="fs-1"></div>
    <p id="feedback_message" class="mt-2 fs-4 fw-bold"></p>
    <p id="feedback_score" class="fs-5 text-primary fw-bold"></p>
    <p id="feedback_total_score" class="fs-6 text-dark"></p>
  </div>
</div>

<div id="countdown_container" class="d-none position-fixed top-0 left-0 w-100 h-100 d-flex flex-column align-items-center justify-content-center bg-dark text-white"
    style="z-index: 9999;">
  <h1 id="countdown_number" class="fw-bold display-1">3</h1>
  <div class="spinner-border text-danger" style="width: 4rem; height: 4rem;" role="status">
    <span class="visually-hidden">Loading...</span>
  </div>
</div>

<div id="waiting_container" <%= "class=d-none" unless @kahoot_game.waiting? %>>
  <%= render 'waiting' %>
</div>

<div id="in_progress_container" <%= "class=d-none" unless @kahoot_game.in_progress? %>>
  <%= render 'in_progress' %>
</div>

<div id="finished_container" <%= "class=d-none" unless @kahoot_game.finished? %>>
  <%= render 'finished' %>
</div>

<div id="canceled_container" <%= "class=d-none" unless @kahoot_game.canceled? %>>
  <%= render 'canceled' %>
</div>

<script type="module">
  document.addEventListener("DOMContentLoaded", function() {
    initKahootGameChannel(<%= @kahoot_game.id %>);
    const inProgress = <%= @kahoot_game.in_progress? %>;
    const indexQuestion = <%= @kahoot_game.current_question_index %>;
    if (inProgress && indexQuestion === 0) {
      showLoadingScreen();
    }
  });
</script>