config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  
  resources :game_responses
  resources :questions do
    member do
      get :review
      patch :update_status
    end
  end
  resources :categories_courses
  resources :levels
  resources :categories
  resources :courses
  resources :roles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :game_sessions, only: [:index, :show, :new, :create, :destroy] do
    member do
      get :play
      post :answer
      get :result
    end
    
    collection do
      get :history
    end
  end

  # config/routes.rb
  resources :admin, only: [:index] do
    collection do
      post 'upload_questions', to: 'admin#upload_questions'
    end
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  authenticated :user do
    root to: 'game_sessions#index', as: :authenticated_root
  end

  devise_scope :user do
    unauthenticated do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :users, only: [:index, :edit, :update, :destroy]
  resources :users do
    member do
      get :edit_password
      patch :update_password
    end
  end

  resources :kahoot_games, only: [:new, :create, :show, :destroy] do
    member do
      post :start
      post :submit_answer
      post :next_question
    end

    collection do
      get :history
    end
  end

  resources :kahoot_participants, only: [:new ,:create, :destroy]

  match "*path", to: "application#handle_not_found", via: :all
  
end

app/models/game_session.rb
class GameSession < ApplicationRecord
  belongs_to :user
  belongs_to :category
  belongs_to :level
  has_many :game_responses, dependent: :destroy

  enum status: { in_progress: 0 , finished: 1}
end

app/models/kahoot_game.rb
class KahootGame < ApplicationRecord
  belongs_to :host, class_name: 'User', foreign_key: "host_id"
  belongs_to :category
  belongs_to :level
  has_many :kahoot_participants, dependent: :destroy
  has_many :kahoot_questions, dependent: :destroy
  has_many :questions, through: :kahoot_questions

  enum status: { waiting: 0, in_progress: 1, finished: 2, canceled: 3 }

  validates :status, presence: true

  NUMBER_OF_QUESTIONS_PER_KAHOOT = 3

  def add_questions
    return true if questions.any?

    if level.name = "mix"
      selected_questions = Question.where(category: category, status: :approved).order(Arel.sql("RANDOM()")).limit(NUMBER_OF_QUESTIONS_PER_KAHOOT)
    else
      selected_questions = Question.where(category: category, level: level, status: :approved).order(Arel.sql("RANDOM()")).limit(NUMBER_OF_QUESTIONS_PER_KAHOOT)
    end

    selected_questions.each_with_index do |question, index|
      kahoot_questions.create!(question: question, order: index)
    end

    self.current_question_index = 0
    save!
  end

  def self.can_add_questions?(category_id, level_id) #Comprobar si hay suficientes preguntas para empezar la partida
    level = Level.find(level_id)
    category = Category.find(category_id)
    if level && category
      if level.name == "mix"
        Question.where(category_id: category_id, status: :approved).count >= NUMBER_OF_QUESTIONS_PER_KAHOOT
      else
        Question.where(category_id: category_id, level_id: level_id, status: :approved).count >= NUMBER_OF_QUESTIONS_PER_KAHOOT
      end
    end
  end

  def current_question
    kahoot_questions.find_by(order: current_question_index)
  end

  def has_next_question?
    current_question_index < (kahoot_questions.count - 1)
  end

  def next_question
    kahoot_questions.find_by(order: current_question_index+1) if has_next_question?
  end

  def advance_question #actualizar el index cuando se va a enviar la siguiente pregunta
    update(current_question_index: current_question_index + 1) if has_next_question?
  end

  def ranking
    kahoot_participants.joins(:user).select("users.username, kahoot_participants.score").order(score: :desc).map { |p| { username: p.username, score: p.score } }
  end
end

app/controllers/game_sessions_controller.rb
class GameSessionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_game_session, only: %i[play answer result destroy]
  before_action :check_game_session_finished, only: :result

  NUMBER_OF_QUESTIONS_PER_GAME = 3

  # GET /game_sessions or /game_sessions.json
  def index
    @levels = Level.all
    case current_user.role.name
    when 'student', 'teacher'
      categories_course = CategoriesCourse.where(course_id: current_user.course_id)
      @categories = Category.where(id: categories_course.pluck(:category_id))
    when 'admin'
      @categories = Category.all
    end
  end
  
  def history
    @game_sessions = current_user.game_sessions.order(created_at: :desc) 
  end

  def show
    @game_session = current_user.game_sessions.find(params[:id])
    @game_responses = @game_session.game_responses.includes(:question)
  end

  # POST /game_sessions or /game_sessions.json
  def create
    @category = Category.find(params[:category_id])
    @level = Level.find(params[:level_id])

    if @level.name.include?('mix')
      @questions = Question.where(category: @category, status: :approved).order(Arel.sql("RANDOM()")).limit(NUMBER_OF_QUESTIONS_PER_GAME)
    else
      @questions = Question.where(category: @category, level: @level, status: 1).order(Arel.sql("RANDOM()")).limit(NUMBER_OF_QUESTIONS_PER_GAME)
    end

    if @questions.empty?
      redirect_to game_sessions_path, alert: "No hay preguntas disponibles para esta categoría y nivel."
      return
    end

    @game_session = GameSession.create(user: current_user, category: @category, level: @level, score: 0)

    session[:game_session_id] = @game_session.id
    session[:question_ids] = @questions.map(&:id)
    session[:current_question_index] = 0

    redirect_to play_game_session_path(@game_session)
  end

  def play
    @level = @game_session.level
    @category_name = @game_session.category.name
    current_index = session[:current_question_index]
    question_ids = session[:question_ids]

    if current_index < question_ids.size
      @question = Question.find(question_ids[current_index])
    end
  end

  def answer
    question = Question.find(params[:question_id])
    user_answer = Answer.find(params[:answer_id])

    correct = user_answer.correct
    GameResponse.create(game_session: @game_session, question: question, correct: correct)

    @game_session.increment!(:score, 10) if correct
    session[:current_question_index] += 1

    if session[:current_question_index] >= session[:question_ids].size
      @game_session.update!(status: :finished)
    end

    render json: {
      correct: correct,
      next_question_index: session[:current_question_index] < session[:question_ids].size,
      question_path: play_game_session_path(@game_session),
      result_path: result_game_session_path(@game_session)
    }
  end

  def result
    @responses = @game_session.game_responses.includes(:question)
  end

  # PATCH/PUT /game_sessions/1 or /game_sessions/1.json
  def update
    respond_to do |format|
      if @game_session.update(game_session_params)
        format.html { redirect_to @game_session, notice: "Game session was successfully updated." }
        format.json { render :show, status: :ok, location: @game_session }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /game_sessions/1 or /game_sessions/1.json
  def destroy
    if current_user == @game_session.user
      @game_session.destroy

      respond_to do |format|
        format.html { redirect_to game_sessions_path, status: :see_other, notice: "Partida cancelada." }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game_session
      @game_session = GameSession.find_by(id: params[:id], user: current_user)

      if @game_session.nil? || @game_session.id != session[:game_session_id]
        redirect_to game_sessions_path, alert: "No tienes acceso a esta partida o no es la partida activa."
      end
    end

    # Only allow a list of trusted parameters through.
    def game_session_params
      params.require(:game_session).permit(:category_id, :level_id)
    end

    def check_game_session_finished
      unless @game_session.finished?
        redirect_to play_game_session_path(@game_session), alert: "La partida no ha terminado aún."
      end
    end
end

app/helpers/game_sessions_helper.rb
module GameSessionsHelper

  def get_random_answers(question)
    question.answers.order(Arel.sql("RANDOM()"))
  end

  def get_answers(question)
    question.answers
  end
end

app/views/game_sessions/edit.html.erb
<h1>Editing Game Session</h1>

<%= render 'form', game_session: @game_session %>

<%= link_to 'Show', @game_session %> |
<%= link_to 'Back', game_sessions_path %>

app/views/game_sessions/history.html.erb
<div class="container mt-4">
  <h1 class="mb-4 text-center">Historial de Partidas</h1>

  <div class="table-responsive" style="max-height: 500px; overflow-y: auto; border: 1px solid #ddd; border-radius: 8px;">
    <table class="table table-striped mb-0">
      <thead>
        <tr>
          <th>ID</th>
          <th>Categoría</th>
          <th>Nivel</th>
          <th>Puntuación</th>
          <th>Fecha</th>
          <th>Acción</th>
        </tr>
      </thead>

      <tbody>
        <% @game_sessions.each do |game| %>
          <tr>
            <td><%= game.id %></td>
            <td><%= game.category.name %> (<%= get_course_category(game.category.id) %>)</td>
            <td><span class="badge rounded-pill bg-<%= game.level.get_color %>"><%= game.level.name %></span></td>
            <td><%= game.score %> puntos</td>
            <td><%= game.created_at.strftime("%d/%m/%Y %H:%M") %></td>
            <td><%= link_to "Ver detalles", game_session_path(game), class: "btn btn-primary btn-sm" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <br>
</div>

app/views/game_sessions/index.html.erb
<div class="container d-flex justify-content-center mt-5">
  <div class="card text-center shadow p-4" style="width: 50rem;">
    <h5 class="card-title mb-4">Crear Partida</h5>
    <%= form_with url: game_sessions_path, method: :post do |form| %>
        <div class="row mb-3">
          <%= form.label 'Categoría' , class: "col-sm-2 col-form-label" %>
          <div class="col-sm-10">
            <%= form.collection_select :category_id, @categories, :id, :name, { prompt: "Selecciona una categoría" }, { class: "form-select mb-3", required: true} %>
          </div>
        </div>

        <div class="row mb-3">
          <%= form.label 'Nivel' , class: "col-sm-2 col-form-label" %>
          <div class="col-sm-10">
            <%= form.collection_select :level_id, @levels, :id, :name, { prompt: "Selecciona un nivel" }, { class: "form-select mb-3", required: true} %>
          </div>
        </div>

      <div>
        <%= form.submit "Iniciar Juego", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/game_sessions/play.html.erb
<style>
  .btn-success {
    background-color: #28a745 !important;
    color: white !important;
  }

  .btn-danger {
    background-color: #dc3545 !important;
    color: white !important;
  }

  .answer-button {
    transition: transform 0.2s ease, box-shadow 0.2s ease;
    cursor: pointer;
  }

  .answer-button:hover {
    transform: scale(1.05);
    box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.2);
  }

</style>

<%= render 'partials/overlay' %>

<div class="container py-5">
  <div class="d-flex justify-content-between align-items-center mb-4">
    <h4 class="fw-bold">
      <span class="badge rounded-pill bg-primary">
        Pregunta <%= session[:current_question_index] + 1 %> de <%= session[:question_ids].size %></h4>
      </span>
    <h4 class="fw-bold">
      <span class="badge rounded-pill bg-success">
        Puntuación: <%= @game_session.score %>
      </span>
    </h4>
  </div>

  <div class="text-center mb-5">
    <h5 class="text-muted" title="Categoría"><%= @category_name %> <span title="Nivel" class="badge rounded-pill bg-<%= @level.get_color %>"><%= @level.name %></span></h5>
    <h3 class="fw-bold text-dark" title="Pregunta"><%= @question.question_text %></h3>
  </div>

  <%= form_with url: answer_game_session_path(@game_session), method: :post do |form| %>
    <%= form.hidden_field :question_id, value: @question.id %>
    <%= form.hidden_field :answer_id, id: "selected_answer_id" %>

    <div class="row row-cols-1 row-cols-md-2 g-4">
      <% get_random_answers(@question).each do |answer| %>
        <div class="col">
          <button type="button" class="btn btn-outline-primary btn-lg w-100 py-3 answer-button shadow-sm" data-answer-id="<%= answer.id %>" data-answer-correct="<%= answer.correct %>">
            <%= answer.answer_text %>
          </button>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<% if current_user == @game_session.user %>
  <div class="d-flex justify-content-start mt-4">
    <button type="button" title="Cancelar Partida" class="btn btn-danger text-white" data-bs-toggle="modal" data-bs-target="#cancelGameModal">
      <i class="fas fa-times me-2 text-white"></i>Cancelar Partida
    </button>
  </div>
<% end %>

<div class="modal fade" id="cancelGameModal" tabindex="-1" aria-labelledby="cancelGameModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header bg-danger text-white">
        <h5 class="modal-title" id="cancelGameModalLabel">Confirmar Cancelación</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ¿Estás seguro de que deseas cancelar la partida? Se perderán todos los datos y no podrás recuperarlos.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Volver</button>
        <%= link_to "Sí, cancelar", game_session_path(@game_session), method: :delete, class: "btn btn-danger text-white" %>
      </div>
    </div>
  </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", () => {
    const answerButtons = document.querySelectorAll(".answer-button");
    const answerInput = document.getElementById("selected_answer_id");
    const answerForm = document.querySelector("form");
    const overlay = document.getElementById("overlay");
    const correctAnswerButton = document.querySelector('.answer-button[data-answer-correct="true"]');

    answerButtons.forEach(button => {
      button.addEventListener("click", () => {
        const answerId = button.getAttribute("data-answer-id");
        answerInput.value = answerId;
        
        //Poner aqui un overlay transparente para que no se pueda presionar ningun btn de nuevo
        overlay.classList.remove("d-none");

        fetch(answerForm.action, {
          method: "POST",
          headers: {
            "Content-Type": "application/x-www-form-urlencoded",
            "X-CSRF-Token": document.querySelector('meta[name="csrf-token"]').content
          },
          body: new URLSearchParams(new FormData(answerForm))
        })
          .then(response => response.json())
          .then(data => {
            if (data.correct) {
              button.classList.add("btn-success");
            } else {
              button.classList.add("btn-danger");
              correctAnswerButton.classList.add("btn-success");
            }

            setTimeout(() => {
              overlay.classList.add("d-none");

              if (data.next_question_index) {
                window.location.href = data.question_path;
              } else {
                window.location.href = data.result_path;
              }
            }, 3000);
          })
          .catch(error => console.error("Error:", error));
      });
    });
  });
</script>

app/views/game_sessions/result.html.erb
<div class="container pt-1 pb-5">
  <div class="card shadow-lg">
    <div class="card-body text-center">
      <h1 class="card-title display-4 text-primary">¡Resultado Final!</h1>
      <p class="card-text fs-4">Puntuación Final: <span class="fw-bold text-success"><%= @game_session.score %> puntos</span></p>
    </div>
  </div>

  <div class="mt-4">
    <h3 class="text-center text-secondary mb-4">Resumen de tus respuestas</h3>
    <div class="list-group text-center">
      <% @responses.each_with_index do |response, index| %>
        <div class="list-group-item">
          <p class="fw-bold">Pregunta <%= index + 1 %>: <span class="text-dark"><%= response.question.question_text %></span></p>
          <p class="mb-0">
            <span class="text-muted">Respuesta Correcta:</span> 
            <span class="text-success"><%= response.question.correct_answer_text %></span>
          </p>
          <p class="mb-0">
            <span class="text-muted">Tu Respuesta:</span> 
            <% if response.correct %>
              <span class="text-success">Correcta</span>
            <% else %>
              <span class="text-danger">Incorrecta</span>
            <% end %>
          </p>
        </div>
      <% end %>
    </div>
  </div>

  <div class="text-center mt-5">
    <%= link_to "Jugar de Nuevo", game_sessions_path, class: "btn btn-primary btn-lg px-5 shadow-sm" %>
  </div>
</div>


app/views/game_sessions/show.html.erb
<div class="container mt-4">
  <h1 class="mb-4 text-center">Detalles de la Partida</h1>
  <div class="card shadow-lg p-4">
    <div class="row">
      <div class="col-md-4">
        <p><strong>Categoría: </strong><%= @game_session.category.name %> (<%= get_course_category(@game_session.category.id) %>)</p>
      </div>
      <div class="col-md-2">
         <p><strong>Nivel: <span class="badge rounded-pill bg-<%= @game_session.level.get_color %>"><%= @game_session.level.name %> </strong>
      </div>
      <div class="col-md-3">
        <p><strong>Puntuación:</strong>
        <% if @game_session.score <= 0 %>
          <span class="badge bg-danger"><%= @game_session.score %> puntos</span></p>
        <% else %>
          <span class="badge bg-success"><%= @game_session.score %> puntos</span></p>
        <% end %>
      </div>
      <div class="col-md-3">
        <p><strong>Fecha:</strong> <span class="badge bg-secondary"><%= @game_session.created_at.strftime("%d/%m/%Y %H:%M") %></span></p>
      </div>
    </div>

    <h4 class="mt-4">Preguntas Respondidas</h3>
    <div class="table-responsive" style="max-height: 500px; overflow-y: auto; border: 1px solid #ddd; border-radius: 8px;">
      <table class="table table-hover table-bordered text-center align-middle">
        <thead class="table-dark table-striped mb-0">
          <tr>
            <th>Pregunta</th>
            <th>Resultado</th>
          </tr>
        </thead>
        <tbody>
          <% @game_responses.each do |response| %>
            <tr class="<%= response.correct ? 'table-success' : 'table-danger' %>">
              <td class="text-start"><%= response.question.question_text %></td>
              <td>
                <% if response.correct %>
                  <span class="badge bg-success">✅ Correcta</span>
                <% else %>
                  <span class="badge bg-danger">❌ Incorrecta</span>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="d-flex justify-content-center mt-4">
      <%= link_to "Volver al Historial", history_game_sessions_path, class: "btn btn-outline-dark btn-lg" %>
    </div>
  </div>
  <div class="mb-3"></div>
</div>