config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  
  resources :game_responses
  resources :questions do
    member do
      get :review
      patch :update_status
    end
  end
  resources :categories_courses
  resources :levels
  resources :categories
  resources :courses
  resources :roles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :game_sessions, only: [:index, :show, :new, :create, :destroy] do
    member do
      get :play
      post :answer
      get :result
    end
    
    collection do
      get :history
    end
  end

  # config/routes.rb
  resources :admin, only: [:index] do
    collection do
      post 'upload_questions', to: 'admin#upload_questions'
    end
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  authenticated :user do
    root to: 'game_sessions#index', as: :authenticated_root
  end

  devise_scope :user do
    unauthenticated do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :users, only: [:index, :edit, :update, :destroy]
  resources :users do
    member do
      get :edit_password
      patch :update_password
    end
  end

  resources :kahoot_games, only: [:new, :create, :show, :destroy] do
    member do
      post :start
      post :submit_answer
      post :next_question
    end

    collection do
      get :history
    end
  end

  resources :kahoot_participants, only: [:new ,:create, :destroy]

  match "*path", to: "application#handle_not_found", via: :all
  
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: %i[ show edit update destroy ]

  # GET /answers or /answers.json
  def index
  end

  # GET /answers/1 or /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers or /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: "Answer was successfully created." }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1 or /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: "Answer was successfully updated." }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1 or /answers/1.json
  def destroy
    @answer.destroy

    respond_to do |format|
      format.html { redirect_to answers_path, status: :see_other, notice: "Answer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def answer_params
      params.require(:answer).permit(:answer_text, :correct, :question_id)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= form_with(model: answer) do |form| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
        <% answer.errors.each do |error| %>
          <li><%= error.message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :answer_text %>
    <%= form.text_area :answer_text %>
  </div>

  <div class="field">
    <%= form.label :correct %>
    <%= form.check_box :correct %>
  </div>

  <div class="field">
    <%= form.label :question_id %>
    <%= form.text_field :question_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<h1>Answers</h1>

<table>
  <thead>
    <tr>
      <th>Answer text</th>
      <th>Correct</th>
      <th>Question</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.answer_text %></td>
        <td><%= answer.correct %></td>
        <td><%= answer.question_id %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p>
  <strong>Answer text:</strong>
  <%= @answer.answer_text %>
</p>

<p>
  <strong>Correct:</strong>
  <%= @answer.correct %>
</p>

<p>
  <strong>Question:</strong>
  <%= @answer.question_id %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>